name: Release App Bundle

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Keystore Check
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'music2.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Set Keystore Path
        run: echo "KEYSTORE_FILE=${{ steps.decode_keystore.outputs.filePath }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17 #17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17 #17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Release Bundle
        run: ./gradlew app:bundleRelease
        env:
          KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs

      - name: Setup Authorization with Google Play
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy Bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.ravisharma.playbackmusic
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: 'completed'

