name: Release App Bundle

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Keystore Check
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileDir: .
          fileName: ${{ secrets.KEYSTORE_FILE_NAME }}
          encodedString: ${{ secrets.KEYSTORE_FILE }}

#      - name: Set Keystore Path
#        run: echo "KEYSTORE_FILE=${{ steps.decode_keystore.outputs.filePath }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up JDK #17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17 #17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Release Bundle
        run: ./gradlew app:bundleRelease
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE_NAME }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs

      - name: Deploy Bundle to Google Play
        if: startsWith(github.ref, 'refs/tags/v')
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.PLAY_AUTH_JSON }}
          packageName: com.ravisharma.playbackmusic
          track: internal
          status: 'completed'

