name: Build Release App Bundle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'music2.jks'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Set Keystore File Path
        run: echo "KEYSTORE_FILE=${{ steps.decode_keystore.outputs.filePath }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17 #17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17 #17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs
